### ISSUE TITLE
Rest Controller shouldn't wrap the data in a specific replesentational format

### ISSUE THREAD

**Issue by neoglez** [zfcampus/zf-rest#108]
At the moment the REST controller wraps whatever data is getting in a HalEntity (or Collection). This interferes very badly with the very concept of REST since the controller is already returning an specific representation and taking away the possibility to do content negotiation. For example:
```php
  /**
     * Return single entity
     *
     * @todo   Remove 'resource' from get.post event for 1.0.0
     * @param  int|string $id
     * @return Response|ApiProblem|ApiProblemResponse|HalEntity
     */
    public function get($id)
    {
        $events = $this->getEventManager();
        $events->trigger('get.pre', $this, ['id' => $id]);

        try {
            $entity = $this->getResource()->fetch($id);
        } catch (Throwable $e) {
            return $this->createApiProblemFromException($e);
        } catch (Exception $e) {
            return $this->createApiProblemFromException($e);
        }

        $entity = $entity ?: new ApiProblem(404, 'Entity not found.');

        if ($this->isPreparedResponse($entity)) {
            return $entity;
        }

        // Here is the problem! What happen if I want to return another representation
        // of the same entity?
        $halEntity = $this->createHalEntity($entity);

        $events->trigger('get.post', $this, [
            'id'       => $id,
            'entity'   => $halEntity,
            'resource' => $halEntity,
        ]);

        return $halEntity;
    }
```
These issue is the conceptional problem description whose some side effects are e.g  https://github.com/zfcampus/zf-rest/issues/98 or https://github.com/zfcampus/zf-rest/issues/89

**Comment by Wilt** [comment]
If you check the method `isPreparedResponse`:

    /**
     * @param  mixed $object
     * @return bool
     */
    protected function isPreparedResponse($object)
    {
        if ($object instanceof ApiProblem
            || $object instanceof ApiProblemResponse
            || $object instanceof Response
        ) {
            return true;
        }

        return false;
    }

You can see that if you return either an instance of `ApiProblem`, `ApiProblemResponse` or any other `Response` object from your listener it will return this immediately.

So you can simply create another `Response` object with any `content-type`.

**Comment by neoglez** [comment]
@Wilt Yes, you're right. And you could listen to the event get.post, extract the entity from the Hal container and set it again in the event (thanks to the reference) or you could listen to the MvcEvent::DISPATCH and unwrap the entity or you could..._put here your favorite hack_ but that doesn't change the fact that 

> Rest Controller shouldn't wrap the data in a specific representational format

. As I mentioned in the description is more a conceptually issue. I will close this one thought.
