### ISSUE TITLE
Problem with page_size and max_page_size

### ISSUE THREAD

**Issue by Nanocl** [zfcampus/zf-rest#110]
I have a problem using the page_size and max_page_size of the Zend REST controller for pagination.  
I have the following config.php (snippet):

    'zf-rest' => [
        Resource\DocumentResource::class => [
            'listener' => Resource\DocumentResource::class,
            ...
            'page_size' => 10,
            'min_page_size' => 1,
            'max_page_size' => 250,
            'collection_query_whitelist' => [
                'page_size',
            ],
        ],
    ],

If I make a REST call with

    ?page_size=50

everything works fine and I get a valid json. But if I make the call with

    ?page_size=250

(or an other value greater than 50) then I get an error:

    ApiProblem (416) - Page size is out of range, maximum page size is 50

**Comment by Nanocl** [comment]
I read that it can be a problem of checking the max_page_size against page_size_param because of preventing DoS attacks. But I haven't understand this fact.

**Comment by Wilt** [comment]
Did you set a `page_size_param` in your configuration? (it configures which query param to use for page size).
If you didn't set such parameter the feature will not be active and  it will default to the default page size of 30.

**Comment by Nanocl** [comment]
Yes, I added the page_size_param but it's the same problem: I can't make a call with page_size=250. The maximum valid value is still 50.

**Comment by Wilt** [comment]
I am not sure but something is strange. 
How can max page size be 50 if you do:

        'page_size' => 10,
        'min_page_size' => 1,
        'max_page_size' => 250,
        'collection_query_whitelist' => [
            'page_size',
        ],

and

        'page_size_param' => 'page_size',

and your request has following query param:

        ?page_size=250

The default page size is 30 inside the module from zf-campus, you get the error _maximum page size is 50_ and 50 is nowhere in this code...?
