### ISSUE TITLE
Can't get POST data

### ISSUE THREAD

**Issue by Nanocl** [zfcampus/zf-rest#111]
I've a problem to create a new rest entity. I've the following configuration:

    $inputFilterSpecForStrings = [
        'required' => false,
        'allow_empty' => false,
        'filters' => [
            'no_tags' => [
                'name' => Filter\StripTags::class,
            ],
            'no_newlines' => [
                'name' => Filter\StripNewlines::class,
            ],
            'trim' => [
                'name' => Filter\StringTrim::class,
            ],
        ],
        'validators' => [
            'not_empty' => [
                'name' => Validator\NotEmpty::class,
            ],
        ],
    ];

    return [
        'router' => [
            'routes' => [
                'api' => [
                    'child_routes' => [
                        'rest' => [
                            'child_routes' => [
                                'search-request' => [
                                    'type' => 'segment',
                                    'may_terminate' => true,
                                    'options' => [
                                        'route' => '/search-request',
                                        'defaults' => [
                                        'controller' => Resource\SearchRequestResource::class,
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'service_manager' => [
            'factories' => [
                Resource\SearchRequestResource::class => Resource\SearchRequestResourceFactory::class,
            ],
        ],
        'zf-rest' => [
            Resource\SearchRequestResource::class => [
                'listener' => Resource\SearchRequestResource::class,
                'entity_http_methods' => [
                ],
                'collection_http_methods' => [
                    'POST',
                ],
                'route_name' => 'api/rest/search-request',
                'route_identifier_name' => NULL,
                'collection_query_whitelist' => [
                    Resource\SearchRequestResource::PARAM_FILTER_LOGIN,
                    Resource\SearchRequestResource::PARAM_FILTER_AUTHOR_IDS,
                ],
            ],
        ],
        'zf-content-negotiation' => [
            'controllers' => [
                Resource\SearchRequestResource::class => 'HalJson',
            ],
        ],
        'input_filter_specs' => [
            Resource\SearchRequestResource::class . '\\SearchValidator' => [
                Resource\SearchRequestResource::PARAM_FILTER_LOGIN => $inputFilterSpecForStrings,
                Resource\SearchRequestResource::PARAM_FILTER_AUTHOR_IDS => $inputFilterSpecForStrings,
            ],
        ],
    ];

This is my factory:

    class SearchRequestResourceFactory implements FactoryInterface {
        public function createService(ServiceLocatorInterface $serviceLocator) {
            return $this($serviceLocator, SearchRequestResource::class);
        }

        public function __invoke(ContainerInterface $container, $requestedName, array $options = null) {
            $resource = new SearchRequestResource();

            $inputFilterManager = $container->get('InputFilterManager');
            $searchInputFilter = $inputFilterManager->get(SearchRequestResource::class . '\\SearchValidator');
            $resource->setSearchInputFilter($searchInputFilter);

            return $resource;
        }
    }

And my resource:

    class SearchRequestResource extends AbstractResourceListener {
        const PARAM_FILTER_LOGIN = 'filter_login';
        const PARAM_FILTER_AUTHOR_IDS = 'filter_author_ids';

        private $searchInputFilter;

        public function setSearchInputFilter(InputFilterInterface $searchInputFilter) {
            $this->searchInputFilter = $searchInputFilter;
        }

        public function getSearchInputFilter() {
            return $this->searchInputFilter;
        }

        public function create($data) {
            $searchInputFilter = $this->getSearchInputFilter();

            try {
                $searchInputFilter->setData($params);
            } catch (InvalidArgumentException $e) {
                return new ApiProblem(
                    Response::STATUS_CODE_422,
                    'Failed Validation',
                    null,
                    null,
                    ['validation_messages' => $e->getMessage()]
                );
            }

            if ($searchInputFilter->isValid()) {
                $filterLogin = $searchInputFilter->getValue(self::PARAM_FILTER_LOGIN);
                $filterAuthorIds = $searchInputFilter->getValue(self::PARAM_FILTER_AUTHOR_IDS);

                $searchRequestEntity = new SearchRequestEntity();
                $searchRequestEntity->setLogin($filterLogin);
                $searchRequestEntity->setAuthorIds($filterAuthorIds);

                return $searchRequestEntity->getId();
            }

            return new ApiProblem(
                Response::STATUS_CODE_422,
                'Failed Validation',
                null,
                null,
                [
                    'validation_messages' => array_merge(
                        $searchInputFilter->getMessages()
                    ),
                ]
            );
        }
    }

And then I try to curl some data:

    curl -H "Content-Type: application/json" -d '{"filter_login":"xyz"}' -X POST http://example.com/api/rest/search-request

The error I got is:

    Zend\InputFilter\BaseInputFilter::setData expects an array or Traversable argument; received NULL

**Comment by diego-sorribas** [comment]
I think that the variable $params here $searchInputFilter->setData($params); does not exists in the context.
