### ISSUE TITLE
delete method 422 Unprocessable Entity

### ISSUE THREAD

**Issue by rifzy** [zfcampus/zf-rest#93]
* Connection #0 to host ############### left intact
{"type":"http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html","title":"Unprocessable Entity","status":422,"detail":"Unable to delete entity."}

```php
public function delete($id)
	{
		$sql = new Sql($this->adapter);
		$delete = $sql->delete('consumer_friends');
		$delete->where(array('id_consumer_friend' => $id));
		$query = $sql->prepareStatementforSqlObject($delete);
		$results = $query->execute();
		return true;
	}
```

resource.php
```php
public function delete($id)
    {
        $this->mapper->delete($id);
    }
```

can you help me please? 
thank you :)

**Comment by snapshotpl** [comment]
Your `delete` method in resource should return boolean

**Comment by rifzy** [comment]
thank you dude, i made a stupid mistake. Thank you for answering really fast :) have a nice day

**Comment by spengilley** [comment]
Looks like this can be closed...

**Comment by NagarajuKasa** [comment]
Hi @spengilley 

is it possible to return custom json while deleting record using apigility?

like:- return new \ZF\ApiProblem\ApiProblemResponse(new \ZF\ApiProblem\ApiProblem(455, 'Member has been deleted'));

Please help me i should return message.

thanks

**Comment by Wilt** [comment]
@spengilley that should be a front-end implementation. You could show such a message after you got a 204 response from the server after sending a DELETE request.

**Comment by spengilley** [comment]
It wasn't me :)
