### ISSUE TITLE
add Content-Location header to POST responses

### ISSUE THREAD

**Issue by BreiteSeite** [zfcampus/zf-rest#95]
Quote from the [RFC 7231: Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content](https://tools.ietf.org/html/rfc7231#section-3.1.4.2):

> For a 201 (Created) response to a state-changing method, a
> Content-Location field-value that is identical to the Location
> field-value indicates that this payload is a current
> representation of the newly created resource.

ZF-Rest already makes specific assumptions about the response, as for example if a HAL-Entity is returned and the HAL entity has a self link, this link is added to the location header to retrieve the resource there.

According to the RFC quoted above, we should also add the Content-Location header to indicate to the clients, the response from the POST is the same response the client would get if it would follow the location header.

**Comment by Wilt** [comment]
Content-Location header can also be used for invalidation after update or delete:

http://tools.ietf.org/html/rfc2616#section-13.10

So correctly implementing such a header is more then just adding it for 201 responses...
